In [1]:
import pandas as pd
import warnings
import os

warnings.filterwarnings("ignore")

In [2]:
df_garantia = pd.read_excel("docs/garantia.xlsx")
df_garantia = df_garantia.sort_values(by=['DEUDOR', 'PERIODO'])
df_garantia['PERIODO'] = df_garantia['PERIODO'].astype("Int64")
df_garantia['DEUDOR'] = df_garantia['DEUDOR'].astype("Int64")
df_garantia['ACREEDOR'] = df_garantia['ACREEDOR'].astype("Int64")
df_garantia.reset_index(drop=True, inplace=True)
df_garantia.head(5)

,PERIODO,DEUDOR,ACREEDOR,NOMBRE,REGION,ANALISTA,TIPO,GARANTIA_FINAL
0,202401,4070004,700002645,AREVALO MOVIL S.A.C. - AMOVIL S.A.C.,CENTRO,JUAN CARLOS HUATAY,DAC TELCO 1,187523.03
1,202402,4070004,700002645,AREVALO MOVIL S.A.C. - AMOVIL S.A.C.,CENTRO,JUAN CARLOS HUATAY,DAC TELCO 1,187523.03
2,202403,4070004,700002645,AREVALO MOVIL S.A.C. - AMOVIL S.A.C.,CENTRO,JUAN CARLOS HUATAY,DAC TELCO 1,187523.03
3,202401,4070075,700002479,PROMOTORA FINANCIERA S.A.C.,LIMA,RAQUEL CAYETANO,DAC TELCO 1,0.00
4,202402,4070075,700002479,PROMOTORA FINANCIERA S.A.C.,LIMA,RAQUEL CAYETANO,DAC TELCO 1,0.00

In [3]:
deudores_con_garantia = df_garantia.groupby('DEUDOR')['GARANTIA_FINAL'].transform('sum') != 0
df_garantia = df_garantia[deudores_con_garantia]

In [4]:
df_garantia['DIFERENCIA'] = df_garantia.groupby('DEUDOR')['GARANTIA_FINAL'].diff()

In [5]:
deudores_con_diferencia = df_garantia.groupby('DEUDOR')['DIFERENCIA'].transform('sum') != 0
df_garantia = df_garantia[deudores_con_diferencia]

In [6]:
df_garantia.to_excel("docs/garantia_diferencias.xlsx", index=False)

In [7]:
os.startfile("docs/garantia_diferencias.xlsx")

In [8]:
df_garantia.head(10)

,PERIODO,DEUDOR,ACREEDOR,NOMBRE,REGION,ANALISTA,TIPO,GARANTIA_FINAL,DIFERENCIA
35,202401,4070208,700002386,INOCENCIO HUAMAN ROLIN DISLAC,CENTRO,DIEGO RODRIGUEZ,DAC TELCO 1,20300.00,NaN
36,202402,4070208,700002386,INOCENCIO HUAMAN ROLIN DISLAC,CENTRO,DIEGO RODRIGUEZ,DAC TELCO 1,20300.00,0.00
37,202403,4070208,700002386,INOCENCIO HUAMAN ROLIN DISLAC,CENTRO,DIEGO RODRIGUEZ,DAC TELCO 1,20300.00,0.00
38,202404,4070208,700002386,INOCENCIO HUAMAN ROLIN DISLAC,CENTRO,DIEGO RODRIGUEZ,DAC TELCO 1,29130.94,8830.94
43,202401,4070230,700003175,SELVA TEL.COM E.I.R.L.,CENTRO,YOLANDA OLIVA,DAC TELCO 1,126649.08,NaN
44,202402,4070230,700003175,SELVA TEL.COM E.I.R.L.,CENTRO,YOLANDA OLIVA,DAC TELCO 1,126649.08,0.00
45,202403,4070230,700003175,SELVA TEL.COM E.I.R.L.,CENTRO,YOLANDA OLIVA,DAC TELCO 1,100756.29,-25892.79
46,202404,4070230,700003175,SELVA TEL.COM E.I.R.L.,CENTRO,YOLANDA OLIVA,DAC TELCO 1,100756.29,0.00
101,202401,4070600,700002876,SATELITAL TELECOMUNICACIONES S.A.C.,LIMA,JUAN CARLOS HUATAY,AGENTE TELMEX / RED,37100.00,NaN
102,202402,4070600,700002876,SATELITAL TELECOMUNICACIONES S.A.C.,LIMA,JUAN CARLOS HUATAY,AGENTE TELMEX / RED,37100.00,0.00